# Generated by Django 3.2.9 on 2021-11-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_email', models.EmailField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('uah', 'uah')], max_length=3)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('due_to_date', models.DateField()),
                ('transactionID', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_email', models.EmailField(max_length=100)),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('uah', 'uah')], max_length=3)),
                ('amount', models.PositiveIntegerField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('due_to_date', models.DateField()),
                ('transactionID', models.CharField(max_length=11, unique=True)),
                ('purchased', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
            options={
                'verbose_name': 'Зробити покупку',
                'verbose_name_plural': 'Зробити покупку',
            },
        ),
    ]
