# Generated by Django 3.2.9 on 2021-11-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='translationID',
            new_name='transactionID',
        ),
    ]
