# Generated by Django 3.2.9 on 2021-11-21 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('book', 'book'), ('phone', 'phone'), ('whathces', 'whatches'), ('laptop', 'laptop'), ('freezer', 'freezer'), ('ball', 'ball'), ('TV', 'TV'), ('computer', 'computer')], db_index=True, max_length=20)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(99999.99)])),
                ('availability', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
